/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.triaje_aga;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner sc = new Scanner(System.in);
        boolean continuar = true;
        String continua;
        int mm;
        String pus;
        int ph;
        
        System.out.println("TRIAGE START");
        System.out.println("Para afirmar pulse la tecla 'SI'. Para negar pulse la tecla 'n'.");
        
        while(continuar){
            System.out.println("Se hace una ecografía transtorácica.");
            System.out.println("¿Presenta septos?");
            continua = sc.nextLine();
            sc.reset();
            
            if("s".equals(continua)){
                System.out.println("Deberíamos aplicar un drenaje pleural, fibrinolíticos y antibioterapia.");
                System.out.println("¿Ha tenido una mala evolución en 48-72 horas?");
                continua = sc.nextLine();
                sc.reset();
                
                if("s".equals(continua)){
                    System.out.println("Se debe hacer una ecografía.");
                    System.out.println("¿Persiste el derrame y septos?");
                    continua = sc.nextLine();
                    sc.reset();
                    
                    if("s".equals(continua)){
                        System.out.println("Se hace una videotoracoscopia.");
                        continuar = false;
                        
                    }else if("n".equals(continua)){
                        System.out.println("Continuar tratamiento.");
                        continuar = false;
                    }
                }else if("n".equals(continua)){
                    System.out.println("Continuar tratamiento");
                    continuar = false;
                }
            }else if ("n".equals(continua)){
                System.out.println("¿Presenta dificultad al respirar?");
                continua = sc.nextLine();
                sc.reset();
                
                if("s".equals(continua)){
                    System.out.println("Drenaje pleural y antibioterapia.");
                    System.out.println("¿Se produce empeoramiento en 24-48h?");
                    continua = sc.next();
                    sc.reset();
                            
                    if("s".equals(continua)){
                                
                    }else{
                        System.out.println("Continuar tratamiento.");
                        continuar = false;
                    }
                }else if("n".equals(continua)){
                    System.out.println("Indica los mm.");
                    mm = sc.nextInt();
                    sc.reset();
                    
                    if(mm > 10){
                        System.out.println("Toracocentesis diagnóstica.");
                        System.out.println("¿Tiene pus?");
                        pus = sc.next();
                        sc.reset();
                        
                        System.out.println("Indica el pH.");
                        ph = sc.nextInt();
                        sc.reset();
                        
                        if("s".equals(pus) || ph < 7.2){
                            System.out.println("Drenaje pleural y antibioterapia.");
                            System.out.println("¿Se produce empeoramiento en 24-48h?");
                            continua = sc.next();
                            sc.reset();
                            
                            if("s".equals(continua)){
                                
                            }else{
                                System.out.println("Continuar tratamiento");
                                continuar = false;
                            }
                        }else{
                            System.out.println("Antibioterapia.");
                            System.out.println("¿Se produce empeoramiento en 24-48h?");
                            continua = sc.next();
                            sc.reset();
                            
                            if("s".equals(continua)){
                                
                            }else{
                                System.out.println("Continuar tratamiento");
                                continuar = false;
                            }
                        }
                    }else{
                        System.out.println("Antibioterapia.");
                        System.out.println("¿Se produce empeoramiento en 24-48h?");
                        continua = sc.next();
                        sc.reset();
                            
                        if("s".equals(continua)){
                                
                        }else{
                            System.out.println("Continuar tratamiento");
                            continuar = false;
                        }
                    }
                }
            }
        }
    }
}

